weblums/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using weblums.Filters;
using weblums.Models;
using weblums.Utils;
using System.IO;

namespace weblums.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class AdminController : Controller
    {
        //
        // GET: /Admin/admin

        public ActionResult Index()
        {
            var model = new DashboardModel();

            using (var context = new AdminContext())
            {
                var dictionaries = context.Dictionaries.ToList();

                //descriptions
                model.WelcomeDescription = dictionaries.Single((item) => item.Key == "Welcome").Value;
                model.SpecialtiesDescription = dictionaries.Single((item) => item.Key == "Specialties").Value;
                model.MenuDescription = dictionaries.Single((item) => item.Key == "Menu").Value;
                model.ReservationDescription = dictionaries.Single((item) => item.Key == "Reservation").Value;
                model.ContactDescription = dictionaries.Single((item) => item.Key == "Contact").Value;

                //slides
                model.Slide1 = dictionaries.Single((item) => item.Key == "Slide1").Value;
                model.Slide2 = dictionaries.Single((item) => item.Key == "Slide2").Value;
                model.Slide3 = dictionaries.Single((item) => item.Key == "Slide3").Value;
            }

            return View(model);
        }

        //
        // GET: /Admin/notification

        public ActionResult Notification()
        {
            var reservations = new List<ReservationModel>();
            var messages = new List<MessageModel>();

            using (var context = new AdminContext())
            {
                foreach (var reservation in context.Reservations.Where((item) => item.isRead == null || item.isRead.Value == false).ToList())
                {
                    var item = new ReservationModel();
                    item.Id = reservation.Id;
                    item.Name = reservation.Name;
                    item.Email = reservation.Email;
                    item.isRead = reservation.isRead.HasValue ? reservation.isRead.Value : false;
                    item.isConfirmed = reservation.isConfirmed.HasValue ? reservation.isConfirmed.Value : false;
                    item.Phone = reservation.Phone;
                    item.Size = reservation.Size;
                    item.Date = reservation.Date;
                    item.Time = reservation.Time;
                    item.CreatedDate = reservation.CreatedDate;
                    if (!string.IsNullOrEmpty(reservation.Note))
                    {
                        int length = reservation.Note.Length < 70 ? reservation.Note.Length : 70;
                        item.Note = reservation.Note.Substring(0, length) + "...";
                    }

                    reservations.Add(item);
                }

                foreach (var message in context.Messages.Where((item) => item.isRead == null || item.isRead.Value == false).ToList())
                {
                    var item = new MessageModel();
                    item.Id = message.Id;
                    item.Name = message.Name;
                    item.Email = message.Email;
                    item.isRead = message.isRead.HasValue ? message.isRead.Value : false;
                    item.CreatedDate = message.CreatedDate;
                    if (!string.IsNullOrEmpty(message.Message))
                    {
                        int length = message.Message.Length < 70 ? message.Message.Length : 70;
                        item.Message = message.Message.Substring(0, length) + "...";
                    }

                    messages.Add(item);
                }
            }

            return Json(new { error = false, reservations = reservations.ToArray(), messages = messages.ToArray() }, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Admin/reservations

        public ActionResult Reservations()
        {
            IList<ReservationModel> model = new List<ReservationModel>();

            using (var context = new AdminContext())
            {
                foreach (var reservation in context.Reservations.OrderBy((item) => item.isRead).ToList())
                {
                    var item = new ReservationModel();
                    item.Id = reservation.Id;
                    item.Name = reservation.Name;
                    item.Email = reservation.Email;
                    item.isRead = reservation.isRead.HasValue ? reservation.isRead.Value : false;
                    item.isConfirmed = reservation.isConfirmed.HasValue ? reservation.isConfirmed.Value : false;
                    item.Phone = reservation.Phone;
                    item.Size = reservation.Size;
                    item.Date = reservation.Date;
                    item.Time = reservation.Time;
                    item.CreatedDate = reservation.CreatedDate;
                    if (!string.IsNullOrEmpty(reservation.Note))
                    {
                        int length = reservation.Note.Length < 70 ? reservation.Note.Length : 70;
                        item.Note = reservation.Note.Substring(0, length) + "...";
                    }

                    model.Add(item);
                }
            }

            return View(model);
        }

        //
        // GET: /Admin/reservations/edit

        public ActionResult EditReservation(int id)
        {
            ReservationModel model = new ReservationModel();

            using (var context = new AdminContext())
            {
                var reservation = context.Reservations.Single((item) => item.Id == id);
                model.Id = reservation.Id;
                model.Name = reservation.Name;
                model.Email = reservation.Email;
                model.Phone = reservation.Phone;
                model.Size = reservation.Size;
                model.Date = reservation.Date;
                model.Time = reservation.Time;
                model.Note = reservation.Note;
                model.isConfirmed = reservation.isConfirmed.HasValue ? reservation.isConfirmed.Value : false;
                model.isRead = true;

                reservation.isRead = true;
                context.SaveChanges();
            }

            return View("Reservations.Edit", model);
        }

        //
        // PUT: /Admin/reservations/edit

        [HttpPut]
        [ValidateAntiForgeryToken]
        public ActionResult EditReservation(ReservationModel model)
        {
            try
            {
                using (var context = new AdminContext())
                {
                    var reservation = context.Reservations.Single((item) => item.Id == model.Id);
                    reservation.Name = model.Name;
                    reservation.Email = model.Email;
                    reservation.Phone = model.Phone;
                    reservation.Size = model.Size.Value;
                    reservation.Date = model.Date.Value;
                    reservation.Time = model.Time;
                    reservation.Note = model.Note;
                    reservation.isRead = model.isRead;
                    reservation.isConfirmed = model.isConfirmed;

                    context.SaveChanges();
                }

                return Json(new { error = false, message = "Save succeeded." }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = true, message = "Save failed." }, JsonRequestBehavior.AllowGet);
            }
        }

        //
        // DELETE: /Admin/reservations/delete

        [HttpDelete]
        public ActionResult DeleteReservation(int id)
        {
            try
            {

                using (var context = new AdminContext())
                {
                    var reservation = context.Reservations.Single((item) => item.Id == id);
                    context.Reservations.Remove(reservation);
                    context.SaveChanges();
                }

                return Json(new { error = false, message = "Delete succeeded." }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = true, message = "Delete failed." }, JsonRequestBehavior.AllowGet);
            }
        }

        //
        // GET: /Admin/messages

        public ActionResult Messages()
        {
            IList<MessageModel> model = new List<MessageModel>();

            using (var context = new AdminContext())
            {
                foreach (var message in context.Messages.OrderBy((item) => item.isRead).ToList())
                {
                    var item = new MessageModel();
                    item.Id = message.Id;
                    item.Name = message.Name;
                    item.Email = message.Email;
                    item.isRead = message.isRead.HasValue ? message.isRead.Value : false;
                    item.CreatedDate = message.CreatedDate;
                    if (!string.IsNullOrEmpty(message.Message))
                    {
                        int length = message.Message.Length < 70 ? message.Message.Length : 70;
                        item.Message = message.Message.Substring(0, length) + "...";
                    }

                    model.Add(item);
                }
            }

            return View(model);
        }

        //
        // GET: /Admin/message/view

        public ActionResult ViewMessage(int id)
        {
            MessageModel model = new MessageModel();

            using (var context = new AdminContext())
            {

weblums/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Lam's The Best Grill Restaurant</title>

    @Styles.Render("~/Content/adminStyles")
      
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Belgrano' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Playball' rel='stylesheet' type='text/css'>

  </head>

  <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/admin">Lam's The Best Grills Restaurant</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li id="alertReservations"><a href="/admin/reservations">Reservations <span id="reservationsBadge" class="badge" style="display:none;"></span></a></li>
                    <li id="alertMessages"><a href="/admin/messages">Messages <span id="messagesBadge" class="badge" style="display:none;"></span></a></li>
                    @if (Request.IsAuthenticated) {
                        <li>
                            @using (Html.BeginForm("LogOff", "Admin", FormMethod.Post, new { id = "logoutForm" })) {
                                @Html.AntiForgeryToken()
                            }
                            <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
                        </li>
                    } 
                </ul>
            </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li id="navDashboard"><a href="/admin">Dashboard</a></li>
                    <li id="navSpecialties"><a href="/admin/specialties">News</a></li>
                    <li id="navMenu"><a href="/admin/menu">Menu</a></li>
                    <li id="navReservations"><a href="/admin/reservations">Reservations</a></li>
                    <li id="navMessages"><a href="/admin/messages">Messages</a></li>
                </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                @RenderBody()
            </div>
            </div>
        </div>

        @Scripts.Render("~/Content/adminScripts")
        @RenderSection("scripts", false)

        <script>
            $(function () {
                function refresh() {
                    $.ajax({
                        url: "/admin/notification",
                        type: "GET",
                        dataType: 'json',
                        contentType: false,
                        cache: false,
                        processData: false,
                        success: function (result) {
                            if (result.reservations.length > 0) {
                                $('#reservationsBadge').text(result.reservations.length);
                                $('#reservationsBadge').show();
                            } else {
                                $('#reservationsBadge').hide();
                            }

                            if (result.messages.length > 0) {
                                $('#messagesBadge').text(result.messages.length);
                                $('#messagesBadge').show();
                            } else {
                                $('#messagesBadge').hide();
                            }
                        }
                    });
                };
                refresh();
                setInterval(function () {
                    refresh();
                }
                , 1000 * 60 * 10);
            });
        </script>

  </body>
</html>

weblums/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Lam's The Best Grill Restaurant</title>

    @Styles.Render("~/Content/styles")

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Belgrano' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Playball' rel='stylesheet' type='text/css'>

  </head>

  <body>

    @RenderBody()
    @Scripts.Render("~/Content/scripts")
    @RenderSection("scripts", false)
  </body>
</html>